### ISSUE TITLE
Help on quick start

### ISSUE THREAD

**Issue by manu-kinisi** [mjhea0/flask-basic-registration#8]
I tried cloning this repo and then just quickly following these commands:

export APP_SETTINGS="project.config.DevelopmentConfig"

python manage.py create_db

but it fails with: 
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from flask_script import Manager
  File "/home/manu/kinisi/test-apps/flask-basic-registration/lib/python3.8/site-packages/flask_script/__init__.py", line 14, in <module>
    from flask import Flask
  File "/home/manu/kinisi/test-apps/flask-basic-registration/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/manu/kinisi/test-apps/flask-basic-registration/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/manu/kinisi/test-apps/flask-basic-registration/lib/python3.8/site-packages/itsdangerous/__init__.py)

I am running python3.8 locally, also tried venv.  I did do a pip3 install -r requirements.txt.

I presume I'm not setting up env correctly but if someone more familiar with this repo could  point me in the right direction that would be appreciated or update the quickstart )

Thanks!

**Comment by mjhea0** [comment]
I just updated the dependencies. It should work now.
